name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test --if-present

      - name: Alerta de sucesso no Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "OK ->  **Pipeline concluído com sucesso!** Todos os testes passaram no repositório ${{ github.repository }}."}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Alerta de falha no Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "ERRO ->  **Pipeline falhou!** Verifique os testes no repositório ${{ github.repository }}."}' \
          ${{ secrets.DISCORD_WEBHOOK }}

  docker:
    runs-on: ubuntu-latest
    needs: testes
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push para DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-somativa:latest

      - name: Alerta de sucesso Docker no Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "OK ->  **Imagem Docker publicada com sucesso** no DockerHub!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Alerta de falha Docker no Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "ERRO -> **Falha ao publicar imagem Docker** no DockerHub!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}